Update pdos.py
Quantum-Dynamics-Hub/libra-code pull request #104
Opened 2020-11-15 12:20 UTC by MohammadShakiba

convolve_cp2k_pdos was added

2020-11-16 17:53 UTC, alexvakimov requested changes

2020-11-16 17:53 UTC, alexvakimov commented on src/libra_py/pdos.py
> +def convolve_cp2k_pdos(cp2k_log_file: str, time_step: int, sigma: float, coef: float, npoints: int, energy_conversion: float, angular_momentum_cols: list):
there are relatively many input parameters, so could you please pack them into a dictionary. This way you can use the check_input function (please do) to setup the default values and check for critical inputs

also - do you really need the "energy_conversion" as an input parameter? it is merely a constant. for consistency, please use the "libra_py.units" module

2020-11-16 17:53 UTC, alexvakimov commented on src/libra_py/pdos.py
> +    for i in range( time_step * ( num_levels + 2 ) + 2, ( time_step + 1 ) * ( num_levels + 2 ) ):
make the inputs of the range function the pre-computed variables - don't do the calculations in the range function itself

2020-11-16 17:53 UTC, alexvakimov commented on src/libra_py/pdos.py
> +            gaussian_fun = (coef/(sigma*np.sqrt(2.0*np.pi)))*(np.exp(-0.5*np.power(((energy_grid-float(pdos_sum[i][0])*energy_conversion)/sigma),2)))
perhaps, pre-compute the common pre-factor before the double loop to reduce the computational time

2020-11-17 17:32 UTC, MohammadShakiba reviewed
the input variable is now a dictionary
checking the input dictionary was added using `comn` 
some parts were fixed as mentioned in the comment
some other fixes were also applied
time library was added
the conversion value can be removed or set to 1 but the user will need to multiply the outputs (`energy_grid` and `homo_energy`) by the conversion unit they need. For the average pdos over the MD this should be applied in the `for` loop over the MD pdos files. Here, we set it as default to eV.
the function was tested successfully.

2020-11-17 22:02 UTC, merged